Add new action step

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -12,7 +12,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Install and test
+      - name: Install
+        run: npm ci
+
+      - name: Test and push
         run: |
-          npm ci
-          npm run test
+          if npm test; then
+            echo "Passed!"
+          else
+            echo "Failed!"
+            exit 1
+          fi
